#!/usr/bin/env python

def options(opt):
    opt.load('compiler_cxx')
    opt.load('python')
    opt.load('boost')


def configure(cfg):
    cfg.load('compiler_cxx')
    cfg.load('python')
    cfg.load('boost')

    cfg.check_boost(lib='python')
    cfg.check_python_version(minver=(2,5))
    cfg.check_python_headers()
    

def build(bld):
    bld(
        features       = 'cxx cxxshlib pyext pyembed',
        source         = 'exceptions.cpp',
        use            = [ 'BOOST' ],
        includes       = [ '.', 'generated' ],
        target         = 'my_exceptions',
    )
