#!/usr/bin/env python
import sys, os

def options(opt):
    opt.load('compiler_cxx')
    opt.load('boost')

def configure(cfg):
    cfg.load('compiler_cxx')
    cfg.load('boost')

    cfg.recurse('../../mapping/metis/current')


def build(bld):
    bld.recurse('../../mapping/metis/current')

    bld(
            target         = 'metis',
            features       = 'cxx cprogram',
            source         = 'metis.cpp',
            use            = 'METIS',
            )

    # ECM: parmetis.h does not exist
    #bld(
    #        target         = 'parmetis',
    #        features       = 'cxx cprogram',
    #        source         = 'parmetis.cpp',
    #        use            = 'METIS',
    #        includes       = '/usr/include/mpi',
    #        lib            = 'mpi mpi_cxx',
    #        )
