#!/usr/bin/env python
import sys, os

def options(opt):
    opt.load('compiler_cxx')

def configure(cfg):
    cfg.load('compiler_cxx')

    cfg.env.LIB_SPAWN = ['boost_mpi', 'boost_graph_parallel', 'boost_system', 'boost_serialization']
    cfg.env.CXXFLAGS_SPAWN = [ '-g']

    cfg.check_cfg(path = 'mpicxx', args = '--showme:compile',
            package = '', uselib_store = 'MPI4MPICONFIG')
    cfg.check_cfg(path = 'mpicxx', args = '--showme:link',
            package = '', uselib_store = 'MPI4MPICONFIG')

def build(bld):
    bld(
        target         = 'master',
        features       = 'cxx cprogram',
        source         = 'master_mpi.cpp',
        use            = 'SPAWN MPI4MPICONFIG',
        install_path   = 'bin',
    )

    for i in xrange(2):
        bld(
            target         = 'slave%d'%i,
            features       = 'cxx cprogram',
            source         = 'slave_mpi.cpp slave%d_mpi.cpp'%i,
            use            = 'SPAWN MPI4MPICONFIG',
            install_path   = 'bin',
        )
